- .travis.yml
- bin/test.sh
- composer.json
- fixtures/Bridge/Symfony/SymfonyApp/DoctrineKernel.php
- fixtures/Bridge/Symfony/SymfonyApp/EloquentKernel.php
- phpunit_symfony_proxy_manager_with_doctrine.xml.dist
- phpunit_symfony_proxy_manager_with_eloquent.xml.dist
- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
- src/Bridge/Doctrine/Purger/OrmPurger.php
- src/Loader/FileResolverLoader.php
- src/Loader/MultiPassLoader.php
- src/Loader/PersisterLoader.php
- src/Loader/PurgerLoader.php
- src/Loader/SimpleLoader.php
- tests/Bridge/Symfony/ProxyManager/Doctrine/FidryAliceDataFixturesBundleTest.php
- tests/Bridge/Symfony/ProxyManager/Eloquent/FidryAliceDataFixturesBundleTest.php
- vendor-bin/proxy-manager/composer.json
- Simplify the Travis build (closes #20)
- Add tests for Ocramius ProxyManager support (closes #16)
- Upgraded to Eloquent `~5.3.0` (required by [WouterJEloquentBundle](https://github.com/wouterj/WouterJEloquentBundle))
- The Eloquent bridge requires https://github.com/wouterj/WouterJEloquentBundle/pull/37 to work
> Upgrade library

- src/Bridge/Symfony/Resources/config/doctrine_orm.xml
I would like to have an ability to use different names than "default" for my entity managers when using AliceDataFixtures. Doctrine has default_entity_manager option and it will point specified entity manager name to orm_entity_manager in a container or will use first on the list of configured entity managers.
> Allow using different names than "default" for entity manager.

- README.md
> Add documentation for auto primary key doctrine generators

- src/Loader/PurgerLoader.php
- src/Persistence/PurgeMode.php
- tests/Loader/PurgerLoaderTest.php
- tests/Persistence/PurgeModeTest.php
Trying to keep things simple: the `NO_PURGE` mode is handled in `PurgerLoader`, not in each `PurgerInterface` implementation.
> Add a NO_PURGE mode

- src/Bridge/Doctrine/Purger/Purger.php
> Disable foreign key checks with truncating with MySQL

- src/Loader/PersisterLoader.php
If `$logger` is optional, `$processors` should be too. I also added the missing doc for `$logger`.
> If $logger is optional, $processors should be too

- README.md
Tiny change to clarify transactional test run, mentioning `default_purge_mode`, typos.
> Clarification for PHPUnit transactional testing

- README.md
This PR fixes the documentation of `ProcessorInterface::{pre,post}Process` which got a second parameter some time ago.
> Fix documentation of ProcessorInterface

- .gitattributes
Including test fixtures in the downloadable archive creates confusion for static analysis tools (IDEs, Scrutinizer, etc...) due to the fake classes in them. For instance, when analyzing my project after the upgrade to Alice 3, Scrutinizer decided that `$this->registry->getManager()` in my code was returning a `\Fidry\AliceDataFixtures\Bridge\Doctrine\ORM\FakeEntityManager` rather than a `Doctrine\ORM\EntityManager`.
These files are not needed in the archive.
> Add a gitattribute file to exclude test fixtures

- .gitattributes
- .gitignore
Follow-up of #98 to remove more things.
Only things kept are:
- the `src` folder (of course necessary)
- the `LICENSE` file (mandatory)
- the `README.md` file (that could be discussed)
- the `composer.json` file (composer does not actually care about that one, but some third-party tools are relying on it to identify third-party packages instead of relying on the composer metadata about installed packages)
I also cleaned the gitignore file from outdated unignored files.
> Exclude more root files from the archive

- phpunit.xml.dist
- phpunit_doctrine.xml.dist
- phpunit_doctrine_mongodb.xml.dist
- phpunit_doctrine_phpcr.xml.dist
- phpunit_eloquent.xml.dist
- phpunit_propel2.xml.dist
- phpunit_symfony.xml.dist
- phpunit_symfony_doctrine.xml.dist
- phpunit_symfony_eloquent.xml.dist
- phpunit_symfony_proxy_manager_with_doctrine.xml.dist
- phpunit_symfony_proxy_manager_with_eloquent.xml.dist
- src/Bridge/Doctrine/Purger/Purger.php
- tests/Bridge/Doctrine/Purger/PurgerTest.php
- vendor-bin/proxy-manager/composer.json
Actually I'm facing the same issue with the DELETE purge mode. I got the following error when trying to refresh my database.
> In AbstractMySQLDriver.php line 49:
>                                                                                                                               
>   An exception occurred while executing 'DELETE FROM portal':                                                                 
>                                                                                                                               
>   SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails
> Disable FK checks also on DELETE

- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
- tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
fixes #105
In any case the generator is changed on the metadata, it must be restored afterward.
Otherwise, manual entity persistence after fixture loading will cause troubles.
Tests was added during the feature addition: https://github.com/theofidry/AliceDataFixtures/commit/7053c75de4d5a91c5bd7db43918a907706c7c990#diff-292d5068b7f30308701962493b4cfd57
So if Travis is green, that will prove the condition is not necessary.
Otherwise, we have to find an another way to deal with it, because leaving the metadata at this state is not acceptable.
> Avoid permanent change of the IdGenerator entity metadata

- .gitignore
- .travis.yml
- composer.json
- phpunit.xml.dist
- phpunit_doctrine.xml.dist
- phpunit_doctrine_mongodb.xml.dist
- phpunit_doctrine_phpcr.xml.dist
- phpunit_eloquent.xml.dist
- phpunit_propel2.xml.dist
- phpunit_symfony.xml.dist
- phpunit_symfony_doctrine.xml.dist
- phpunit_symfony_eloquent.xml.dist
- phpunit_symfony_proxy_manager_with_doctrine.xml.dist
- phpunit_symfony_proxy_manager_with_eloquent.xml.dist
- tests/Bridge/Doctrine/Purger/PurgerTest.php
- tests/Bridge/DoctrineMongoDB/Purger/PurgerTest.php
- tests/Bridge/DoctrinePhpCr/Purger/PurgerTest.php
- tests/Bridge/Eloquent/Purger/ModelPurgerTest.php
- tests/Loader/FileResolverLoaderTest.php
- tests/Loader/MultiPassFileLoaderTest.php
- tests/Loader/PersisterLoaderTest.php
- tests/Loader/PurgerLoaderTest.php
- tests/Loader/SimpleLoaderTest.php
- vendor-bin/doctrine/composer.json
- vendor-bin/doctrine_mongodb/composer.json
- vendor-bin/doctrine_phpcr/composer.json
Replaces https://github.com/theofidry/AliceDataFixtures/pull/145, it adds @jmsche [suggestion](https://github.com/theofidry/AliceDataFixtures/pull/145#issuecomment-692077614) and requires explicitly `doctrine/persistance`.
I also added conflict with `zendframework/zend-code` < 3.3.1 because of https://github.com/zendframework/zend-code/pull/158 and with `doctrine/orm` < 2.6.3 because of https://github.com/doctrine/orm/pull/7325.
> Fix PHPUnit deprecations

- .travis.yml
- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
- tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
> Don't disable the id generator if the entity has already been persisted

- fixtures/Bridge/Doctrine/Entity/DummyWithRelation.php
- src/Bridge/Doctrine/IdGenerator.php
- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
- tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
This should solve the problem found in #153 
It also allows to mix fixtures with and without provided ids.
@VincentLanglet would you mind to test this PR with your fixtures set?
And @yakobe could you test with yours?
I checked on my project and this works.
> Keep the ids specified for entities by end users

- src/Bridge/Doctrine/Purger/Purger.php
- tests/Bridge/Doctrine/Purger/PurgerTest.php
When purging data, this library attempts to detect whether MySQL is used by checking the "driver"; if so, it temporarily disables foreign key constraints.
However, some libraries (like Sentry's Symfony bundle) decorate that driver to add functionality like tracing the SQL statements being executed.  Because these decorators do not extend from `AbstractMySQLDriver` this library fails to disable foreign key checks when decorated drivers are being used.  See https://github.com/getsentry/sentry-symfony/issues/503 for an example of this.
I propose that this library should check the **platform** instead of the **driver**.  Platforms describe **what type of database** is being used, versus the drivers which provide **how to interface with that database**.  Because we care more about the "what" …
> Fix MySQL platform detection

- bin/doctrine_purge
- bin/eloquent_migrate
- bin/eloquent_rollback
- cli-config.php
- composer.json
- doctrine-odm-db-settings.php
- doctrine-orm-db-settings.php
- doctrine-phpcr-db-settings.php
- eloquent-db-settings.php
- fixtures/get-param.php
- tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
- tests/Bridge/Doctrine/Purger/PurgerTest.php
- tests/Bridge/Doctrine/autoload.php
- tests/Bridge/DoctrineMongoDB/Persister/ObjectManagerPersisterTest.php
- tests/Bridge/DoctrineMongoDB/Purger/PurgerTest.php
- tests/Bridge/DoctrineMongoDB/autoload.php
- tests/Bridge/DoctrinePhpCr/Persister/ObjectManagerPersisterTest.php
- tests/Bridge/DoctrinePhpCr/Purger/PurgerTest.php
- tests/Bridge/DoctrinePhpCr/autoload.php
- tests/Bridge/Eloquent/Persister/ModelPersisterTest.php
- tests/Bridge/Eloquent/Purger/ModelPurgerTest.php
- tests/Bridge/Eloquent/autoload.php
- tests/Bridge/Symfony/Doctrine/PhpcrLoaderIntegrationTest.php
- vendor-bin/covers-validator/composer.lock
- vendor-bin/doctrine/composer.json
- vendor-bin/php-cs-fixer/composer.lock
This is probably one of the most sneaky and subtle aspect which potentially resulted in flaky tests. Indeed an entity manager does not only contain a connection (which unless you change it causes little issues) but also the UnitOfWork which contains a lot of internal state which sometimes we tamper with or for which the metadata changes from a test to another (which is no good if the old metadata is cached by doctrine somewhere).
In this PR we guarantee that the managers & co. are always fresh
> Ensures managers are not shared within tests

- .github/workflows/tests.yaml
- composer.json
- vendor-bin/proxy-manager/composer.json
- vendor-bin/symfony/composer.json
Some builds still require more work, but I will not wait on them for tagging the release as I am not sure how much more work it will require and I am needed elsewhere
> Enable back various builds

- fixtures/Bridge/Doctrine/Entity/DummyWithRelatedCascadePersist.php
- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
Fixes the error introduced in #198 (and release 1.5.0) during persisting an entity with a nullable ManyToOne relation:
```
TypeError: Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister::getMetadata(): Argument #2 ($object) must be of type object, null given, called in src/Bridge/Doctrine/Persister/ObjectManagerPersister.php on line 158
```
See failed build with the test without fix: https://github.com/javer/AliceDataFixtures/actions/runs/1607767589
And successful build with the test and fix: https://github.com/javer/AliceDataFixtures/actions/runs/1607777714
> Fix persisting entity with nullable ManyToOne relation

- fixtures/Bridge/Symfony/SymfonyApp/config/config.yml
- fixtures/Bridge/Symfony/SymfonyApp/config/config_symfony_3.yml
- tests/Bridge/Symfony/Doctrine/PhpcrLoaderIntegrationTest.php
- vendor-bin/doctrine/composer.json
- vendor-bin/doctrine_mongodb/composer.json
- vendor-bin/doctrine_phpcr/composer.json
- vendor-bin/proxy-manager/composer.json
- vendor-bin/symfony/composer.json
I saw this error [on CI](https://github.com/theofidry/AliceDataFixtures/runs/5066863207?check_suite_focus=true) :
> PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in /home/runner/work/AliceDataFixtures/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php:165
`doctrine/annotations` was a dependency of `doctrine/persistence` until https://github.com/doctrine/persistence/pull/197/files
It has to be a strong dependency now.
> Require doctrine/annotations

- .github/workflows/tests.yaml
The CI was blocked because there is no more runner available with Ubuntu 18.
> ci: Run on ubuntu latest

- .github/workflows/tests.yaml
PHP-CS-Fixer is not executed in the CI hence there is no point installing it there.
> ci: Do not install PHP-CS-Fixer

- .github/workflows/tests.yaml
- Makefile
- docker-compose.yml
Starting from Mongodb version 6.0 mongo was replaced by mongosh
> ci: Migrate from mongo to mongosh

- Makefile
- fixtures/Bridge/Doctrine/Entity/DummyWithProperty.php
- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
- tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
restoring the class metadata in the metadata factory does not restore the one doctrine has cached in the `class` property of it's persisters....
downstream this might lead to unexpected behaviour: when the id generator has been replaced with this library's `IdGenerator`, the basic entity persister does not recognise it as an id generator and treats the identity field as one which can be used for inserts in the [`BasicEntityPersister::getInsertColumnList`](https://github.com/doctrine/orm/blob/94144e122779098c156098fc9bb6791e53192086/src/Persisters/Entity/BasicEntityPersister.php#L1443-L1451) method 
this can lead to `Invalid parameter number: number of bound variables does not match number of tokens` errors on subsequent inserts of the entity manager. this change will fix that
> fix: clear entity persister on restoring class metadata

- src/Bridge/Symfony/DependencyInjection/FidryAliceDataFixturesExtension.php
The base extension available in HttpKernel only adds support for registering some classes to be added in the cache warmer of the doctrine/annotations parser, compared to the base class of the DI component. As annotations are not supported anymore in Symfony 7, this base class has been deprecated in Symfony 7.1.
As this bundle does not rely on the extra feature, it can use the base class from DI directly.
> Remove usage of the deprecated base extension from HttpKernel

- README.md
- composer.json
- doctrine-phpcr-db-settings.php
- fixtures/Bridge/Doctrine/PhpCrDocument/Dummy.php
- fixtures/Bridge/Doctrine/PhpCrDocument/DummySubClass.php
- fixtures/Bridge/Doctrine/PhpCrDocument/MappedSuperclassDummy.php
- tests/Bridge/DoctrinePhpCr/autoload.php
Seeing how little changes in the tests the library is still compatible with 1.x so it should not require any changes. However for executing the tests, to ligthen the burden on this library, I am migrating to 2.0 minimum which removes support for annotations in favour of attributes.
> feat: Bump min version supported by Doctrine/PHPCR to 2.0

- composer.json
Currently this libraries allows Doctrine ORM 3 despite not being compatible with it. It was not causing an issue locally due to `doctrine/annotations`.
> fix: Tighten the Doctrine ORM dependency conflict

- src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
The method was too confusing as it was not highlightning the fact that it may have multiple side-effects.
> refactor: Rename the getMetadata() method
