bin/clear_cache.sh
bin/console
bin/test.sh
fixtures/Bridge/Symfony/SymfonyApp/Bundle/DoctrineBundle.php
fixtures/Bridge/Symfony/SymfonyApp/Bundle/DoctrineConnectionlessPass.php
fixtures/Bridge/Symfony/SymfonyApp/DoctrineKernelWithInvalidDatabase.php
fixtures/Bridge/Symfony/SymfonyApp/EloquentKernelWithInvalidDatabase.php
fixtures/Bridge/Symfony/SymfonyApp/config/config_doctrine_with_invalid_database.yml
fixtures/Bridge/Symfony/SymfonyApp/config/config_eloquent_with_invalid_database.yml
fixtures/Util.php
phpunit_symfony.xml.dist
src/Bridge/Eloquent/Persister/ModelPersister.php
src/Bridge/Eloquent/Purger/ModelPurger.php
tests/Bridge/Symfony/Doctrine/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/Doctrine/ORMLoaderIntegrationTest.php
tests/Bridge/Symfony/Eloquent/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/Eloquent/ORMLoaderIntegrationTest.php
tests/Bridge/Symfony/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/ProxyManager/Doctrine/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/ProxyManager/Doctrine/LazyIntegrationTest.php
tests/Bridge/Symfony/ProxyManager/Eloquent/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/ProxyManager/Eloquent/LazyIntegrationTest.php
vendor-bin/symfony/composer.json

- Add a test to ensure Symfony can be booted without requiring a database connection
- Ensure there is no Kernel corruption anywhere

Fix proxy manager support

---

src/Loader/PersisterLoader.php
src/Persistence/Persister/NullPersister.php
src/ProcessorInterface.php
tests/Loader/PersisterLoaderTest.php
tests/Loader/ProcessorIndexTest.php
tests/Persistence/Persister/NullPersisterTest.php

Closes https://github.com/hautelook/AliceBundle/issues/212.

Pass the fixture ID to the processors

---

composer.json
src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
src/Bridge/Doctrine/Purger/OrmPurger.php
src/Bridge/Eloquent/Persister/ModelPersister.php
src/Bridge/Eloquent/Purger/ModelPurger.php
src/Loader/FileResolverLoader.php
src/Loader/MultiPassLoader.php
src/Loader/PersisterLoader.php
src/Loader/PurgerLoader.php
src/Loader/SimpleLoader.php
tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
tests/Bridge/Doctrine/Purger/OrmPurgerTest.php
tests/Bridge/Eloquent/Persister/ModelPersisterTest.php
tests/Bridge/Eloquent/Purger/ModelPurgerTest.php
tests/Bridge/Symfony/Doctrine/ORMLoaderIntegrationTest.php
tests/Loader/FileResolverLoaderTest.php
tests/Loader/MultiPassFileLoaderTest.php
tests/Loader/PersisterLoaderTest.php
tests/Loader/PurgerLoaderTest.php
tests/Loader/SimpleLoaderTest.php

Fix a few BC breaks introduce in `v3.0.0-beta.2`

Upgrade to nelmio/alice v3.0.0-beta.3

---

src/Bridge/Doctrine/Persister/ObjectManagerPersister.php

Fixes https://github.com/theofidry/AliceDataFixtures/issues/51

Don't invoke 'clear()' anymore

---

src/Bridge/Doctrine/Persister/ObjectManagerPersister.php

Calculate metadata calculation lazily

---

src/Loader/FileResolverLoader.php
src/Loader/PurgerLoader.php

See https://github.com/hautelook/AliceBundle/pull/371

Make some loaders persister aware

---

src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php
tests/Bridge/DoctrineMongoDB/Persister/ObjectManagerPersisterTest.php

[Doctrine] Support for disabling ID generators if ID provided in fixture

---

README.md

Add doc entry on how to use it in tests

---

src/ProcessorInterface.php
tests/Loader/ProcessorIndexTest.php

From what I gathered inspecting the code base, these methods have no return value.

These methods are not supposed to have return values

---

README.md
vendor-bin/doctrine_mongodb/composer.json
vendor-bin/doctrine_phpcr/composer.json

Add documentation for MongoDB and PHPCR

---

.travis.yml
README.md
composer.json
fixtures/Bridge/Symfony/SymfonyApp/IsolatedKernel.php
tests/Bridge/Symfony/Doctrine/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/Doctrine/MongodbLoaderIntegrationTest.php
tests/Bridge/Symfony/Doctrine/ORMLoaderIntegrationTest.php
tests/Bridge/Symfony/Doctrine/PhpcrLoaderIntegrationTest.php
vendor-bin/doctrine_phpcr/composer.json
vendor-bin/eloquent/composer.json
vendor-bin/proxy-manager/composer.json
vendor-bin/symfony/composer.json

Waiting on some third-party deps.

Allow Symfony 4.0

---

README.md
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Loader/PurgerLoader.php
tests/Loader/PurgerLoaderTest.php

So that we have this option too :)

Added "no_purge" option to Symfony configuration

---

composer.json

resolves https://github.com/hautelook/AliceBundle/issues/279

set conflict rule in composer.json

---

src/Bridge/Doctrine/Persister/ObjectManagerPersister.php

Follow up of #91
/cc @umpirsky

Make the ID generator configuration easier to override

---

fixtures/Bridge/Doctrine/MongoDocument/DummyWithEmbeddable.php

It only fix a test from `make test_doctrine_odm_bridge`.
I didn't managed to fix the other tests. I think that this can still be merged as is.

Fix test_doctrine_odm_bridge test

---

src/Bridge/Doctrine/Persister/ObjectManagerPersister.php

Prevent IdGenerator from decorating itself

---

.gitignore
fixtures/Bridge/Eloquent/Migration/FakeMigrationRepository.php
tests/Bridge/DoctrinePhpCr/autoload.php
tests/Bridge/Symfony/Doctrine/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/Eloquent/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/ProxyManager/Doctrine/FidryAliceDataFixturesBundleTest.php
tests/Bridge/Symfony/ProxyManager/Eloquent/FidryAliceDataFixturesBundleTest.php

Ensures the cache directory is cleaned up

Cleanup the cache directory

---

src/Bridge/Symfony/DependencyInjection/Configuration.php

Signed-off-by: Aurélien Fontaine <a.fontaine@naitways.com>

remove deprecation for Symfony 5.4

---

fixtures/Bridge/Doctrine/Entity/AnotherDummy.php
fixtures/Bridge/Doctrine/Entity/DummyWithRelatedCascadePersist.php
src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
tests/Bridge/Doctrine/Persister/ObjectManagerPersisterTest.php

Add ID disabled generation with cascade persist

---

README.md

set link to CI

---

.github/workflows/tests.yaml
Makefile

Only install the necessary vendor bins for the given tests

ci: Reduce the number of installations

---

src/Bridge/Doctrine/Purger/Purger.php

Rebased version of #267.
Closes #267.

fix: Disable foreign keys check for purge

---

Makefile
composer.json
rector.php
vendor-bin/rector/composer.json

Adds rector. Note that in this project it is not meant to be run
continuously, hence it is not added to the CI.

chore: Introduce Rector 
